### ISSUE TITLE
issue: converting packs from single file.

### ISSUE THREAD

**Issue by redoxahmii** [sahaj-b/wayvibes#2]
I really like using `eg-oreo` that is provided as default from mechvibes and tried the converter in `rustyvibes` previously as well to make it work with that but it never worked for me properly.
```
Failed to initialize sound: eg-oreo/26.ogg
```
Had high hopes it might work on this but it seems that the issue is same.
My guess would be due to the audio file being `ogg` so if you could provide some info about how this should work it would helpful.

The pack provided in it by default does not properly work with the `u` key.

**Comment by redoxahmii** [comment]
One more thing i would like to add is you should provide a method in README to uninstall this as well.

**Comment by sahaj-b** [comment]
`miniaudio` doesn't support all ogg files as `dr_vorbis` isn't ready ([see this issue](https://github.com/mackron/miniaudio/issues/255)). 
I can use a custom decoder (`libvorbis`) using  [minivorbis](https://github.com/edubart/minivorbis) , I prefer not to add another dependency (libvorbis) just to support OGG files. Instead, it’s easier to convert OGG files to WAV or MP3 using the following command:
```bash
for f in *.ogg; do ffmpeg -i "$f" "${f%.ogg}.wav"; done
sed -i 's/\.ogg/\.wav/g' config.json #change extensions in config.json
rm *.ogg
```
I will include this in README
